---

name: Linux gcc-13

on: [push, pull_request, workflow_dispatch]

jobs:
  linux_gcc13:
    uses: ./.github/workflows/CI-common.yml
    with:
      runner: ubuntu-24.04
      conan_pr_build: ./.github/conanProfiles/ubuntu24.txt
      conan_pr_host: ./.github/conanProfiles/linux-gcc13.txt
      cmake_profile: conan-x86_64-linux-gcc-13
      compiler_name: gcc
