---

name: Linux gcc-13

on: [push, pull_request, workflow_dispatch]

jobs:
  skip_duplicate:
    runs-on: ubuntu-24.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          skip_after_successful_duplicate: true

  linux_gcc13:
    uses: ./.github/workflows/CI-common.yml
    needs: skip_duplicate
    with:
      runner: ubuntu-24.04
      conan_pr_build: ./.github/conanProfiles/ubuntu24.txt
      conan_pr_host: ./.github/conanProfiles/linux-gcc13.txt
      cmake_profile: conan-x86_64-linux-gcc-13
      compiler_name: gcc
      should_skip: ${{needs.skip_duplicate.outputs.should_skip}}
