---

name: Linux clang-17

on: [push, pull_request, workflow_dispatch]

env:
  cmake_profile: conan-x86_64-linux-clang-17
  conan_pr_build: ./.github/conanProfiles/ubuntu24.txt
  conan_pr_host: ./.github/conanProfiles/linux-clang17.txt
  vcpkg_base: '$HOME/vcpkg'

jobs:
  skip_duplicate:
    runs-on: ubuntu-24.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          skip_after_successful_duplicate: true

  linux_clang17:
    runs-on: ubuntu-24.04
    needs: skip_duplicate
    if: ${{ !fromJSON(needs.skip_duplicate.outputs.should_skip) }}
    strategy:
      matrix:
        build_type: [Debug, Release]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - id: build_type
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ matrix.build_type }}

      - name: "[setup] Install vcpkg"
        run: python '.github/scripts/installVcpkg.py' --dest "${{ env.vcpkg_base }}"

      - name: "[setup] Install apt-get packages"
        run: |
          sudo apt update
          sudo apt install -y ninja-build libc++-17-dev valgrind

      - name: "[setup] Install conan"
        run: |
          pipx install conan
          pipx ensurepath

      - name: "[setup] Cache conan packages"
        uses: actions/cache@v4
        with:
          path: ~/.conan2/p
          key: ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }}

      - name: "[build] conan install"
        run: conan install . -pr:b=${{ env.conan_pr_build }} -pr:h=${{ env.conan_pr_host }} -s:h build_type=${{ matrix.build_type }} --build=missing

      - name: "[build] cmake config"
        run: >
          cmake . --preset ${{ env.cmake_profile }}
          -D "GUSTAVE_CONAN_BUILD_PROFILE=${{ env.conan_pr_build }}"
          -D "GUSTAVE_CONAN_HOST_PROFILE=${{ env.conan_pr_host }}"
          -D "GUSTAVE_VCPKG_ROOT=${{ env.vcpkg_base }}"

      - name: "[build/setup] Install Python venvs"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }} --target venvs

      - name: "[build] Build"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }}

      - name: "[build] Run unit tests"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }} --target run-unit-tests

      - name: "[build] Run tool tests"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }} --target run-tool-tests

      - name: "[build] Run memcheck tests"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }} --target run-memcheck-tests

      - name: "[build] Run tutorials"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }} --target run-tutorials

      - name: "[build] Run packaging tests"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }} --target run-packaging-tests
