---

name: Windows VS-2022

on: [push, pull_request, workflow_dispatch]

env:
  cmake_profile: conan-x86_64-windows-msvc-193
  drMemory_base: '$HOME/drMemory'
  conan_pr_build: ./.github/conanProfiles/windows2022.txt
  conan_pr_host: ./.github/conanProfiles/windows-msvc193.txt
  vcpkg_base: '$HOME/vcpkg'

jobs:
  skip_duplicate:
    runs-on: ubuntu-24.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          skip_after_successful_duplicate: true

  windows_msvc193:
    runs-on: windows-2022
    if: needs.skip_duplicate.outputs.should_skip != 'true'
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
      - uses: actions/checkout@v4

      - id: build_type
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ matrix.build_type }}

      - uses: ilammy/msvc-dev-cmd@v1

      - name: "[setup] Install vcpkg"
        run: python '.github/scripts/installVcpkg.py' --dest "${{ env.vcpkg_base }}"

      - name: "[setup] Install DrMemory"
        run: python '.github/scripts/msvc/installDrMemory.py' --dest "${{ env.drMemory_base }}"

      - name: "[setup] Install conan"
        run: |
          pipx install conan
          pipx ensurepath

      - name: "[setup] Cache conan packages"
        uses: actions/cache@v4
        with:
          path: ~/.conan2/p
          key: ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }}

      - name: "[build] conan install"
        run: conan install . -pr:b=${{ env.conan_pr_build }} -pr:h=${{ env.conan_pr_host }} -s:h build_type=${{ matrix.build_type }} --build=missing

      - name: "[build] cmake config"
        run: >
          cmake . --preset ${{ env.cmake_profile }}
          -D "GUSTAVE_MEMCHECKER_PATH=${{ env.drMemory_base }}/bin64"
          -D "GUSTAVE_CONAN_BUILD_PROFILE=${{ env.conan_pr_build }}"
          -D "GUSTAVE_CONAN_HOST_PROFILE=${{ env.conan_pr_host }}"
          -D "GUSTAVE_VCPKG_ROOT=${{ env.vcpkg_base }}"

      - name: "[build/setup] Install Python venvs"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }} --target venvs

      - name: "[build] Build"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }}

      - name: "[build] Run unit tests"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }} --target run-unit-tests

      - name: "[build] Run tool tests"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }} --target run-tool-tests

      # Disabled drMemory test because of false positives that can't be reproduced outside Github's runners.
      #- name: "[build] Run memcheck tests"
      #  if: matrix.build_type == 'Release'
      #  run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }} --target run-memcheck-tests

      - name: "[build] Run tutorials"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }} --target run-tutorials

      - name: "[build] Run packaging tests"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }} --target run-packaging-tests
